/**
 * Seed des vraies subventions culturelles francaises.
 *
 * Usage:
 *   DATABASE_URL="postgresql://..." npx tsx scripts/seed-cultural-grants.ts
 *
 * Ou via Railway:
 *   railway run -- npx tsx scripts/seed-cultural-grants.ts
 */

import { db } from "../server/db";
import { grants } from "../shared/schema";
import type { InsertGrant } from "../shared/schema";

const CULTURAL_GRANTS: InsertGrant[] = [
  // ========== MUSIQUE ==========
  {
    title: "Aide a la creation musicale - CNM",
    organization: "Centre National de la Musique (CNM)",
    description: "Soutien financier aux projets de creation d'oeuvres musicales originales dans tous les genres : musiques actuelles, classique, jazz, electronique, musiques du monde. Couvre les frais de composition, arrangement, enregistrement studio et production artistique. Le CNM est le principal financeur public de la musique en France.",
    eligibility: "Artistes-auteurs, compositeurs ou producteurs musicaux professionnels. Affiliation a une societe d'auteurs (SACEM, SACD) recommandee. Projet de creation avec budget previsionnel detaille. Ouvert aux artistes individuels et structures.",
    amount: null,
    amountMin: 5000,
    amountMax: 30000,
    deadline: "Permanent",
    frequency: "3 sessions par an (mars, juin, octobre)",
    url: "https://cnm.fr/aides/aide-a-la-creation-musicale/",
    contactEmail: "aides@cnm.fr",
    contactPhone: "01 53 59 22 00",
    grantType: ["Subvention directe", "Aide a la creation"],
    eligibleSectors: ["Musique", "Musiques actuelles", "Jazz", "Classique", "Electronique"],
    geographicZone: ["National"],
    maxFundingRate: 70,
    coFundingRequired: "Oui - minimum 30% du budget",
    processingTime: "3 a 4 mois",
    applicationDifficulty: "Moyen",
    acceptanceRate: 40,
    annualBeneficiaries: 250,
    preparationAdvice: "Soignez la qualite de vos maquettes audio (3-5 titres MP3). Budget detaille poste par poste avec devis. Mettez en avant l'originalite artistique et les retombees du projet.",
    status: "active",
  },
  {
    title: "Aide au developpement d'artiste - CNM",
    organization: "Centre National de la Musique (CNM)",
    description: "Accompagnement des artistes musicaux en phase de developpement de carriere. Financement de la production phonographique, promotion, tournee, clips, communication digitale. Destinee aux artistes emergents avec un debut de parcours professionnel.",
    eligibility: "Structures de production ou management accompagnant un artiste. L'artiste doit avoir au moins 1 sortie commerciale ou 20 dates de concert. Projet sur 12-18 mois.",
    amount: null,
    amountMin: 10000,
    amountMax: 50000,
    deadline: "Permanent",
    frequency: "4 sessions par an",
    url: "https://cnm.fr/aides/aide-au-developpement-dartiste/",
    contactEmail: "aides@cnm.fr",
    grantType: ["Subvention directe", "Aide au developpement"],
    eligibleSectors: ["Musique", "Musiques actuelles", "Pop", "Rap", "Rock", "Electronique"],
    geographicZone: ["National"],
    maxFundingRate: 60,
    processingTime: "2 a 3 mois",
    applicationDifficulty: "Moyen",
    acceptanceRate: 35,
    preparationAdvice: "Montrez une trajectoire ascendante : streaming, dates live, presse. Business plan sur 18 mois avec objectifs chiffres.",
    status: "active",
  },
  {
    title: "Aide a la diffusion de spectacle vivant musical - CNM",
    organization: "Centre National de la Musique (CNM)",
    description: "Soutien aux tournees et diffusion de spectacles musicaux en France et a l'international. Couvre les frais de deplacements, hebergement, cachets, regie technique pour les dates de tournee.",
    eligibility: "Producteurs ou tourneurs de spectacles musicaux, minimum 5 dates programmees. Structure professionnelle avec SIRET. Planning de tournee confirme.",
    amount: null,
    amountMin: 3000,
    amountMax: 20000,
    deadline: "Permanent",
    frequency: "Sessions trimestrielles",
    url: "https://cnm.fr/aides/",
    contactEmail: "aides@cnm.fr",
    grantType: ["Subvention directe", "Aide a la diffusion"],
    eligibleSectors: ["Musique", "Spectacle vivant musical"],
    geographicZone: ["National", "International"],
    maxFundingRate: 50,
    processingTime: "6 a 8 semaines",
    applicationDifficulty: "Facile",
    acceptanceRate: 55,
    preparationAdvice: "Fournissez les contrats de cession ou lettres de programmation pour chaque date. Budget tournee detaille par poste.",
    status: "active",
  },
  {
    title: "Bourse de creation SACEM",
    organization: "SACEM - Societe des Auteurs Compositeurs et Editeurs de Musique",
    description: "Bourse destinee a financer des projets musicaux ambitieux : creation d'oeuvres, projets interdisciplinaires, innovations musicales. Valorise l'originalite artistique et la qualite de la demarche creative.",
    eligibility: "Compositeurs et auteurs membres de la SACEM. Projet de creation original avec note d'intention artistique detaillee. Budget entre 5000 et 80000 euros.",
    amount: null,
    amountMin: 3000,
    amountMax: 15000,
    deadline: null,
    frequency: "Annuel - 1 session",
    url: "https://aide-aux-projets.sacem.fr/",
    contactEmail: "actionculturelle@sacem.fr",
    grantType: ["Bourse", "Aide a la creation"],
    eligibleSectors: ["Musique", "Creation sonore", "Musique de film"],
    geographicZone: ["National"],
    maxFundingRate: 60,
    processingTime: "4 a 5 mois",
    applicationDifficulty: "Difficile",
    acceptanceRate: 25,
    annualBeneficiaries: 100,
    preparationAdvice: "Le jury est compose de professionnels exigeants. Votre projet doit etre veritablement original. Les maquettes audio de qualite sont essentielles.",
    status: "active",
  },
  {
    title: "Aide aux projets - ADAMI",
    organization: "ADAMI - Societe civile pour l'Administration des Droits des Artistes et Musiciens Interpretes",
    description: "Soutien financier aux projets artistiques portes par des artistes-interpretes : enregistrement, spectacle vivant, clip, creation. L'ADAMI finance les artistes-interpretes (musiciens, comediens, danseurs) dans leurs projets personnels.",
    eligibility: "Artistes-interpretes professionnels affilies a l'ADAMI. Au moins 1 projet anterieur justifiable. Budget previsionnel entre 5000 et 50000 euros.",
    amount: null,
    amountMin: 2000,
    amountMax: 12000,
    deadline: null,
    frequency: "Permanent - depot toute l'annee",
    url: "https://www.adami.fr/que-fait-ladami-pour-moi/cherche-financement-projet-artistique/",
    contactEmail: "contact@adami.fr",
    grantType: ["Subvention directe", "Aide a la creation", "Aide a la diffusion"],
    eligibleSectors: ["Musique", "Theatre", "Danse", "Spectacle vivant"],
    geographicZone: ["National"],
    maxFundingRate: 50,
    processingTime: "6 a 8 semaines",
    applicationDifficulty: "Facile",
    acceptanceRate: 60,
    annualBeneficiaries: 500,
    preparationAdvice: "Mettez en avant votre parcours d'interprete et la viabilite du projet. Joignez des extraits de votre travail precedent.",
    status: "active",
  },
  {
    title: "Aide aux projets - SPEDIDAM",
    organization: "SPEDIDAM - Societe de Perception et de Distribution des Droits des Artistes-Interpretes",
    description: "Financement de projets de spectacle vivant, d'enregistrement et de creation impliquant des artistes-interpretes. Couvre les cachets des artistes, la production et la diffusion.",
    eligibility: "Structures professionnelles (association, SARL, etc.) employant des artistes-interpretes. Projet avec au moins 3 artistes-interpretes remuneres. Budget previsionnel detaille.",
    amount: null,
    amountMin: 1500,
    amountMax: 15000,
    deadline: null,
    frequency: "Permanent - commissions mensuelles",
    url: "https://www.spedidam.fr/aides-financieres/",
    contactEmail: "aides@spedidam.fr",
    grantType: ["Subvention directe"],
    eligibleSectors: ["Musique", "Danse", "Theatre", "Spectacle vivant"],
    geographicZone: ["National"],
    maxFundingRate: 40,
    processingTime: "4 a 6 semaines",
    applicationDifficulty: "Facile",
    acceptanceRate: 65,
    preparationAdvice: "Joignez les contrats ou intentions d'embauche des artistes-interpretes. Le nombre d'emplois artistiques crees est un critere cle.",
    status: "active",
  },

  // ========== SPECTACLE VIVANT ==========
  {
    title: "ADSV - Aides deconcentrees au spectacle vivant",
    organization: "DRAC - Ministere de la Culture",
    description: "Aide majeure du Ministere de la Culture pour les equipes independantes de spectacle vivant : theatre, danse, cirque, arts de la rue, marionnette. Financement de la creation, diffusion et fonctionnement des compagnies. Attribuee par les DRAC dans chaque region.",
    eligibility: "Compagnies et equipes artistiques professionnelles (association ou SARL). Au moins 2 creations anterieures. Implantation dans la region de la DRAC sollicitee. Projet de creation ou plan de diffusion sur 1-3 ans.",
    amount: null,
    amountMin: 5000,
    amountMax: 60000,
    deadline: null,
    frequency: "Annuel - depot janvier-mars selon les DRAC",
    url: "https://www.culture.gouv.fr/Aides-Demarches/Appels-a-projets-Aides/Aides-deconcentrees-au-spectacle-vivant-ADSV",
    grantType: ["Subvention directe", "Aide a la creation", "Aide au fonctionnement"],
    eligibleSectors: ["Theatre", "Danse", "Cirque", "Arts de la rue", "Marionnette", "Spectacle vivant"],
    geographicZone: ["National"],
    maxFundingRate: 50,
    processingTime: "3 a 6 mois",
    applicationDifficulty: "Difficile",
    acceptanceRate: 30,
    annualBeneficiaries: 1400,
    preparationAdvice: "Dossier artistique complet avec historique de la compagnie, note d'intention du prochain spectacle, budget sur 3 ans, lettres de soutien de programmateurs.",
    status: "active",
  },
  {
    title: "Aide a la creation theatrale - ONDA",
    organization: "ONDA - Office National de Diffusion Artistique",
    description: "L'ONDA accompagne la diffusion des oeuvres du spectacle vivant en France. Aide financiere aux lieux de diffusion qui programment des compagnies independantes. Permet aux compagnies de tourner dans des lieux qui n'auraient pas les moyens de les accueillir.",
    eligibility: "Lieux de diffusion ou festivals programmant des compagnies independantes. La compagnie doit etre soutenue par une DRAC ou un label. Minimum 3 dates de diffusion du spectacle.",
    amount: null,
    amountMin: 1000,
    amountMax: 8000,
    deadline: null,
    frequency: "Permanent",
    url: "https://www.onda.fr/",
    contactEmail: "info@onda.fr",
    grantType: ["Aide a la diffusion", "Garantie financiere"],
    eligibleSectors: ["Theatre", "Danse", "Cirque", "Spectacle vivant"],
    geographicZone: ["National"],
    processingTime: "4 a 6 semaines",
    applicationDifficulty: "Moyen",
    preparationAdvice: "C'est le lieu d'accueil qui fait la demande, pas la compagnie. Travaillez avec vos programmateurs pour monter le dossier.",
    status: "active",
  },

  // ========== ARTS VISUELS ==========
  {
    title: "Aide individuelle a la creation - CNAP",
    organization: "CNAP - Centre National des Arts Plastiques",
    description: "Soutien financier aux artistes plasticiens pour la realisation d'un projet de creation. Couvre les frais de production, materiaux, location d'atelier, recherche. Le CNAP est l'organisme de reference pour les arts visuels en France.",
    eligibility: "Artistes plasticiens professionnels residant en France. Projet de creation original dans le champ des arts visuels : peinture, sculpture, photographie, installation, video, art numerique, performance. Dossier artistique avec portfolio.",
    amount: null,
    amountMin: 3000,
    amountMax: 12000,
    deadline: null,
    frequency: "Annuel - depot automne",
    url: "https://www.cnap.fr/aides-et-commandes/aide-individuelle-a-la-creation",
    contactEmail: "info@cnap.fr",
    grantType: ["Bourse", "Aide a la creation"],
    eligibleSectors: ["Arts visuels", "Peinture", "Sculpture", "Photographie", "Installation", "Art numerique", "Video", "Performance"],
    geographicZone: ["National"],
    processingTime: "4 a 6 mois",
    applicationDifficulty: "Difficile",
    acceptanceRate: 15,
    annualBeneficiaries: 80,
    preparationAdvice: "Portfolio de 20 images max, note d'intention claire et concise. Le jury est tres selectif — votre demarche artistique doit etre singuliere et bien articulee.",
    status: "active",
  },
  {
    title: "Aide au premier catalogue - CNAP",
    organization: "CNAP - Centre National des Arts Plastiques",
    description: "Aide a l'edition du premier catalogue monographique d'un artiste plasticien. Couvre les frais d'impression, graphisme, textes critiques, traduction. Destinee aux artistes emergents n'ayant jamais publie de catalogue.",
    eligibility: "Artistes plasticiens professionnels n'ayant jamais publie de catalogue monographique. Partenariat avec un editeur ou une galerie. Projet editorial defini.",
    amount: null,
    amountMin: 2000,
    amountMax: 8000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.cnap.fr/aides-et-commandes",
    grantType: ["Aide a l'edition"],
    eligibleSectors: ["Arts visuels", "Photographie", "Art contemporain"],
    geographicZone: ["National"],
    applicationDifficulty: "Moyen",
    preparationAdvice: "Presentez une maquette editoriale et un devis d'imprimeur. Le texte critique est un plus fort.",
    status: "active",
  },
  {
    title: "Allocation de recherche - DRAC",
    organization: "DRAC - Direction Regionale des Affaires Culturelles",
    description: "Aide individuelle attribuee par chaque DRAC aux artistes plasticiens de la region pour soutenir un temps de recherche et experimentation. Permet de financer une periode sans production destinee a la vente, focalisee sur la recherche pure.",
    eligibility: "Artistes plasticiens professionnels residant dans la region de la DRAC. Parcours artistique justifie (expositions, residences). Projet de recherche artistique defini.",
    amount: null,
    amountMin: 2000,
    amountMax: 6000,
    deadline: null,
    frequency: "Annuel - depot printemps",
    url: "https://www.culture.gouv.fr/Regions",
    grantType: ["Allocation", "Aide a la recherche"],
    eligibleSectors: ["Arts visuels", "Art contemporain", "Design", "Metiers d'art"],
    geographicZone: ["Regional"],
    applicationDifficulty: "Moyen",
    acceptanceRate: 25,
    preparationAdvice: "Contactez votre DRAC regionale pour les dates exactes. Le projet de recherche doit se distinguer d'un projet de production classique.",
    status: "active",
  },

  // ========== CINEMA / AUDIOVISUEL ==========
  {
    title: "Avance sur recettes avant realisation - CNC",
    organization: "CNC - Centre National du Cinema et de l'Image Animee",
    description: "Aide selective phare du CNC pour le cinema francais. Avance remboursable sur les recettes futures du film. Finance l'ecriture et le developpement de longs metrages de cinema. Commission de professionnels du cinema.",
    eligibility: "Auteurs-realisateurs de long metrage cinema. Scenario complet ou traitement detaille. Societe de production francaise attachee au projet. Premiere ou deuxieme oeuvre fortement encouragees.",
    amount: null,
    amountMin: 30000,
    amountMax: 500000,
    deadline: null,
    frequency: "Permanent - 6 commissions par an",
    url: "https://www.cnc.fr/professionnels/aides-et-financements/cinema/production/avance-sur-recettes-avant-realisation_191224",
    contactEmail: null,
    contactPhone: "01 44 34 34 40",
    grantType: ["Avance remboursable", "Aide a la production"],
    eligibleSectors: ["Cinema", "Long metrage"],
    geographicZone: ["National"],
    processingTime: "3 a 4 mois",
    applicationDifficulty: "Tres difficile",
    acceptanceRate: 15,
    annualBeneficiaries: 60,
    preparationAdvice: "Le scenario doit etre abouti. La commission est tres selective — casting, producteur, budget previsionnel doivent etre credibles. Les premiers films ont un bonus.",
    status: "active",
  },
  {
    title: "Aide a l'ecriture de scenario - CNC",
    organization: "CNC - Centre National du Cinema et de l'Image Animee",
    description: "Aide financiere pour l'ecriture ou la reecriture de scenarios de longs metrages, courts metrages ou films d'animation. Permet au scenariste de se consacrer a l'ecriture a temps plein.",
    eligibility: "Scenaristes et realisateurs. Synopsis ou traitement d'au moins 5 pages. Pas besoin de producteur attache a ce stade.",
    amount: null,
    amountMin: 7500,
    amountMax: 30000,
    deadline: null,
    frequency: "3 sessions par an",
    url: "https://www.cnc.fr/professionnels/aides-et-financements/cinema/ecriture-et-developpement",
    grantType: ["Bourse", "Aide a l'ecriture"],
    eligibleSectors: ["Cinema", "Animation", "Court metrage"],
    geographicZone: ["National"],
    processingTime: "2 a 3 mois",
    applicationDifficulty: "Moyen",
    acceptanceRate: 20,
    preparationAdvice: "Note d'intention sincere sur votre vision du film. Le traitement doit montrer votre capacite narrative. CV avec travaux precedents.",
    status: "active",
  },
  {
    title: "Aide au court metrage - CNC",
    organization: "CNC - Centre National du Cinema et de l'Image Animee",
    description: "Soutien a la production de courts metrages (fiction, animation, documentaire, experimental). Aide tres accessible pour les jeunes realisateurs. Premier tremplin vers le long metrage.",
    eligibility: "Societe de production francaise. Realisateur avec ou sans experience anterieure. Scenario complet. Duree du film inferieure a 60 minutes.",
    amount: null,
    amountMin: 10000,
    amountMax: 75000,
    deadline: null,
    frequency: "Permanent - commissions mensuelles",
    url: "https://www.cnc.fr/professionnels/aides-et-financements/court-metrage",
    grantType: ["Subvention directe", "Aide a la production"],
    eligibleSectors: ["Cinema", "Court metrage", "Animation", "Documentaire"],
    geographicZone: ["National"],
    processingTime: "2 a 3 mois",
    applicationDifficulty: "Moyen",
    acceptanceRate: 25,
    annualBeneficiaries: 200,
    preparationAdvice: "Le scenario prime sur tout. Equipe technique credible. Budget realiste. Les premiers films sont bienvenus.",
    status: "active",
  },

  // ========== LIVRE / ECRITURE ==========
  {
    title: "Bourse de creation litteraire - CNL",
    organization: "CNL - Centre National du Livre",
    description: "Bourse d'ecriture pour les auteurs de litterature (roman, poesie, essai, theatre, BD, jeunesse). Permet a l'auteur de se consacrer a l'ecriture d'une oeuvre en cours. Le CNL est l'organisme central du soutien au livre en France.",
    eligibility: "Auteurs ayant deja publie au moins 1 ouvrage a compte d'editeur. Projet d'ecriture en cours avec synopsis ou extrait. Nationalite francaise ou resident en France.",
    amount: null,
    amountMin: 5000,
    amountMax: 30000,
    deadline: null,
    frequency: "Annuel - depot mars et octobre",
    url: "https://www.centrenationaldulivre.fr/aides/bourse-de-creation",
    contactEmail: "aide.creation@centrenationaldulivre.fr",
    grantType: ["Bourse", "Aide a la creation"],
    eligibleSectors: ["Litterature", "Poesie", "Essai", "Theatre", "BD", "Jeunesse", "Livre"],
    geographicZone: ["National"],
    processingTime: "3 a 4 mois",
    applicationDifficulty: "Moyen",
    acceptanceRate: 30,
    annualBeneficiaries: 200,
    preparationAdvice: "Extrait d'au moins 30 pages + synopsis detaille. CV litteraire avec publications. La qualite de l'ecriture est le critere n.1.",
    status: "active",
  },
  {
    title: "Bourse de residence d'ecriture - CNL",
    organization: "CNL - Centre National du Livre",
    description: "Financement d'une residence d'ecriture de 1 a 3 mois dans un lieu partenaire du CNL. L'auteur est loge et recoit une bourse mensuelle pour se consacrer exclusivement a l'ecriture.",
    eligibility: "Auteurs ayant au moins 1 publication a compte d'editeur. Projet d'ecriture defini. Selection sur dossier artistique.",
    amount: null,
    amountMin: 2000,
    amountMax: 6000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.centrenationaldulivre.fr/aides",
    grantType: ["Bourse", "Residence"],
    eligibleSectors: ["Litterature", "Poesie", "Essai", "Traduction", "Livre"],
    geographicZone: ["National"],
    applicationDifficulty: "Facile",
    acceptanceRate: 40,
    preparationAdvice: "Motivez le choix de la residence et son lien avec votre projet d'ecriture. Planning de travail sur la duree de la residence.",
    status: "active",
  },
  {
    title: "Bourse de traduction - SOFIA",
    organization: "SOFIA - Societe Francaise des Interets des Auteurs de l'Ecrit",
    description: "Aide financiere aux traducteurs litteraires pour la traduction d'oeuvres vers ou depuis le francais. Couvre le temps de travail du traducteur sur un projet specifique.",
    eligibility: "Traducteurs litteraires professionnels. Contrat d'edition signe ou intention d'editeur. Oeuvre source identifiee.",
    amount: null,
    amountMin: 1500,
    amountMax: 8000,
    deadline: null,
    frequency: "2 sessions par an",
    url: "https://www.la-sofia.org/",
    grantType: ["Bourse"],
    eligibleSectors: ["Traduction", "Litterature", "Livre"],
    geographicZone: ["National"],
    applicationDifficulty: "Moyen",
    preparationAdvice: "Joignez le contrat d'edition et un extrait traduit de 10-15 pages. Presentez l'interet de l'oeuvre pour le lectorat francophone.",
    status: "active",
  },

  // ========== DANSE ==========
  {
    title: "Aide a la creation choregraphique - DRAC",
    organization: "DRAC - Direction Regionale des Affaires Culturelles",
    description: "Aide specifique aux compagnies choregraphiques pour la creation de nouvelles pieces. Financement de la recherche, des repetitions, de la production et de la creation lumiere/son. Attribuee par chaque DRAC regionale.",
    eligibility: "Compagnies de danse professionnelles (association ou SARL). Choregraphe avec parcours justifie. Implantation dans la region. Projet de creation avec calendrier de repetitions et perspectives de diffusion.",
    amount: null,
    amountMin: 5000,
    amountMax: 25000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.culture.gouv.fr/Regions",
    grantType: ["Subvention directe", "Aide a la creation"],
    eligibleSectors: ["Danse", "Danse contemporaine", "Danse hip-hop", "Choregraphie"],
    geographicZone: ["Regional"],
    applicationDifficulty: "Moyen",
    acceptanceRate: 30,
    preparationAdvice: "Note d'intention choregraphique claire. Planning de creation avec lieux de repetition confirmes. Lettres d'interet de programmateurs.",
    status: "active",
  },

  // ========== MULTIDISCIPLINAIRE / TRANSVERSAL ==========
  {
    title: "Aide aux projets innovants et numeriques - DRAC",
    organization: "DRAC - Direction Regionale des Affaires Culturelles",
    description: "Soutien aux projets artistiques utilisant les technologies numeriques : art numerique, creation interactive, realite virtuelle, intelligence artificielle appliquee a l'art, spectacle augmente. Encourage les croisements entre art et technologie.",
    eligibility: "Artistes ou structures culturelles avec composante numerique/technologique dans le projet. Implantation regionale. Projet innovant dans sa forme ou son contenu.",
    amount: null,
    amountMin: 3000,
    amountMax: 15000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.culture.gouv.fr/Regions",
    grantType: ["Subvention directe", "Aide a la creation"],
    eligibleSectors: ["Art numerique", "Arts visuels", "Musique", "Spectacle vivant", "Multimedia", "Realite virtuelle"],
    geographicZone: ["Regional"],
    applicationDifficulty: "Moyen",
    preparationAdvice: "Montrez la dimension innovante du projet. Decrivez les technologies utilisees de facon accessible. Partenariats tech bienvenus.",
    status: "active",
  },
  {
    title: "Creative Europe - Cooperation europeenne",
    organization: "Commission Europeenne - Programme Creative Europe",
    description: "Le plus gros programme de financement culturel europeen. Finance la cooperation entre organisations culturelles de differents pays de l'UE. Projets de co-creation, tournees europeennes, echanges artistiques, formations croisees. Budget significatif mais process exigeant.",
    eligibility: "Structure juridique (association, societe) obligatoire. Consortium d'au moins 3 organisations de 3 pays UE differents (small-scale) ou 5 organisations de 5 pays (large-scale). Le porteur de projet est le chef de file du consortium.",
    amount: null,
    amountMin: 60000,
    amountMax: 200000,
    deadline: null,
    frequency: "Annuel - depot en janvier-fevrier",
    url: "https://culture.ec.europa.eu/creative-europe",
    grantType: ["Subvention europeenne", "Cooperation"],
    eligibleSectors: ["Tous secteurs culturels", "Interdisciplinaire"],
    geographicZone: ["International", "Union Europeenne"],
    maxFundingRate: 80,
    processingTime: "6 a 9 mois",
    applicationDifficulty: "Tres difficile",
    acceptanceRate: 12,
    preparationAdvice: "Commencez la constitution du consortium 6-12 mois a l'avance. Mobilisez les points de contact Creative Europe nationaux. Le formulaire est complexe — prevoyez 2-3 mois de redaction.",
    status: "active",
  },
  {
    title: "Aide a la residence artistique - Fondation de France",
    organization: "Fondation de France",
    description: "Soutien aux residences artistiques accueillant des artistes de toutes disciplines pour un temps de creation. Finance l'hebergement, la bourse de l'artiste et les frais de production. La Fondation de France soutient fortement la creation contemporaine.",
    eligibility: "Structures d'accueil en residence (association, collectivite, lieu culturel). Artistes de toutes disciplines. Projet de residence de 1 a 6 mois avec objectifs artistiques definis.",
    amount: null,
    amountMin: 3000,
    amountMax: 15000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.fondationdefrance.org/fr/cat-culture",
    grantType: ["Subvention directe", "Residence"],
    eligibleSectors: ["Tous secteurs culturels", "Arts visuels", "Musique", "Spectacle vivant", "Litterature"],
    geographicZone: ["National"],
    applicationDifficulty: "Moyen",
    acceptanceRate: 20,
    preparationAdvice: "Mettez en avant l'ancrage territorial et les interactions avec le public local. La dimension participative est un plus.",
    status: "active",
  },
  {
    title: "Aide aux artistes de moins de 30 ans",
    organization: "Fondation Nationale des Arts Graphiques et Plastiques (FNAGP)",
    description: "Bourse destinee aux jeunes artistes plasticiens de moins de 30 ans pour les accompagner dans leur debut de carriere. Soutient la creation, l'atelier et la premiere exposition.",
    eligibility: "Artistes plasticiens de moins de 30 ans residant en France. Diplome d'ecole d'art ou parcours autodidacte justifie. Portfolio de travaux recents.",
    amount: null,
    amountMin: 2000,
    amountMax: 8000,
    deadline: null,
    frequency: "Annuel",
    url: "https://www.fnagp.fr/",
    grantType: ["Bourse", "Aide aux jeunes artistes"],
    eligibleSectors: ["Arts visuels", "Peinture", "Sculpture", "Photographie", "Art contemporain"],
    geographicZone: ["National"],
    applicationDifficulty: "Moyen",
    acceptanceRate: 20,
    preparationAdvice: "Portfolio solide de 15-20 images. Note d'intention sur votre demarche artistique. Montrez un debut de parcours (expositions collectives, residences).",
    status: "active",
  },
  {
    title: "Aide au projet artistique et culturel - Region Ile-de-France",
    organization: "Region Ile-de-France",
    description: "Soutien regional aux projets artistiques et culturels en Ile-de-France. Tous les secteurs culturels sont eligibles : musique, theatre, danse, arts visuels, cinema, livre. Priorite aux projets de proximite et accessibilite culturelle.",
    eligibility: "Structures culturelles (association, societe) implantees en Ile-de-France. Projet se deroulant principalement en Ile-de-France. Budget minimum 5000 euros.",
    amount: null,
    amountMin: 3000,
    amountMax: 30000,
    deadline: null,
    frequency: "Permanent",
    url: "https://www.iledefrance.fr/aides-regionales-culture",
    grantType: ["Subvention directe"],
    eligibleSectors: ["Tous secteurs culturels"],
    geographicZone: ["Ile-de-France"],
    maxFundingRate: 50,
    processingTime: "2 a 3 mois",
    applicationDifficulty: "Moyen",
    preparationAdvice: "Mettez en avant l'impact territorial francilien et l'accessibilite du projet au plus grand nombre.",
    status: "active",
  },
];

async function seedGrants() {
  console.log(`\nInsertion de ${CULTURAL_GRANTS.length} subventions culturelles de reference...\n`);

  let inserted = 0;
  let skipped = 0;

  for (const grant of CULTURAL_GRANTS) {
    // Verifier si une grant avec le meme titre existe deja
    const existing = await db.select({ id: grants.id })
      .from(grants)
      .where(eq(grants.title, grant.title))
      .limit(1);

    if (existing.length > 0) {
      console.log(`  SKIP (existe deja) : ${grant.title}`);
      skipped++;
      continue;
    }

    await db.insert(grants).values(grant);
    console.log(`  OK : ${grant.title}`);
    inserted++;
  }

  console.log(`\nTermine : ${inserted} inserees, ${skipped} deja presentes.`);
  console.log(`Total grants en base : ${(await db.select({ id: grants.id }).from(grants).where(eq(grants.status, "active"))).length}`);
  process.exit(0);
}

// Need the eq import
import { eq } from "drizzle-orm";

seedGrants().catch((err) => {
  console.error("Erreur:", err);
  process.exit(1);
});
